# docker-compose.yml (for local development)
# version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - PAYMENT_SERVICE_URL=http://payment-service:4001
      - ORDER_SERVICE_URL=http://order-service:4002
      - NOTIFICATION_SERVICE_URL=http://notification-service:4003
    networks:
      - my-shared-network

  
networks:
  my-shared-network:
    external: true