# docker-compose.yml (for local development)
version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PAYMENT_SERVICE_URL=http://localhost:3001
      - ORDER_SERVICE_URL=http://localhost:3002
      - NOTIFICATION_SERVICE_URL=http://localhost:3003
